# Based on https://nikitabobko.github.io/AeroSpace/config-examples#i3-like-config

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
# Disabled in favor of i3-like AutoRaise.app:
# https://github.com/Dimentium/homebrew-autoraise/blob/11608becc696e1b0cadcb93a7059e50378cd3dc6/README.md?plain=1#L33
# alt-left = 'focus left'
# alt-down = 'focus down'
# alt-up = 'focus up'
# alt-right = 'focus right'

alt-cmd-left = 'move left'
alt-cmd-down = 'move down'
alt-cmd-up = 'move up'
alt-cmd-right = 'move right'

alt-h = 'split horizontal'
alt-v = 'split vertical'

alt-f = 'fullscreen'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-cmd-r = 'mode resize'

[mode.resize.binding]
left = 'resize width -50'
up = 'resize height +50'
down = 'resize height -50'
right = 'resize width +50'
esc = 'mode main'
