#!/bin/zsh
# This hook is sourced after a new virtualenv is activated.

# Install utility libraries
pip install awscli ipython

# Bind to project directory
project=`basename $VIRTUAL_ENV`
project_dir=$PROJECT_HOME/$project
mkdir -p $project_dir
setvirtualenvproject $VIRTUAL_ENV $project_dir

# Create Sublime Text project file inside ~/.virtualenvs
[[ -f $VIRTUAL_ENV/../$project.sublime-project ]] || cat << EOM > $VIRTUAL_ENV/../$project.sublime-project
{
    "folders":
    [
        {
            "folder_exclude_patterns": [
                "__pycache__",
                "node_modules"
            ],
            "path": "$project_dir"
        }
    ]
}
EOM
