#!/usr/bin/env bash
# Pings Google to check internet connectivity (more trustworthy than NetworkManager applet)

set -eu

echo NET
echo NET
if ping -c1 -q 8.8.8.8 > /dev/null; then
  echo '#00ff00'
else
  echo '#ff0000'
fi
